language: node_js
node_js: node
cache:
  directories:
    - node_modules
services: postgresql
before_script:
  - sudo apt-get -qq update # qq for less output
  - psql -c 'create database travis_ci_test;' -U postgres
install:
  - npm install
  - npm run buildEnv
  - npm run setup:server
  - npm run setup:client
script:
  - npm run build &
  - sleep 10 
  - npm run start:server &
  - sleep 10